// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_2024_color_ from "./routes/2024/[color].jsx";
import * as $_2024_index from "./routes/2024/index.jsx";
import * as $_2024_summerbay from "./routes/2024/summerbay.jsx";
import * as $_2024_wolfe from "./routes/2024/wolfe.jsx";
import * as $api_middleware from "./routes/api/_middleware.ts";
import * as $api_hue from "./routes/api/hue.ts";
import * as $index from "./routes/index.tsx";
import * as $robots_txt from "./routes/robots.txt.tsx";
import * as $_2024_Background from "./islands/2024/Background.jsx";
import * as $_2024_Heart from "./islands/2024/Heart.jsx";
import * as $_2024_LaserWaveform from "./islands/2024/LaserWaveform.jsx";
import * as $_2024_SummerBay from "./islands/2024/SummerBay.jsx";
import * as $_2024_Wolf from "./islands/2024/Wolf.jsx";
import * as $NewHeart from "./islands/NewHeart.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/2024/[color].jsx": $_2024_color_,
    "./routes/2024/index.jsx": $_2024_index,
    "./routes/2024/summerbay.jsx": $_2024_summerbay,
    "./routes/2024/wolfe.jsx": $_2024_wolfe,
    "./routes/api/_middleware.ts": $api_middleware,
    "./routes/api/hue.ts": $api_hue,
    "./routes/index.tsx": $index,
    "./routes/robots.txt.tsx": $robots_txt,
  },
  islands: {
    "./islands/2024/Background.jsx": $_2024_Background,
    "./islands/2024/Heart.jsx": $_2024_Heart,
    "./islands/2024/LaserWaveform.jsx": $_2024_LaserWaveform,
    "./islands/2024/SummerBay.jsx": $_2024_SummerBay,
    "./islands/2024/Wolf.jsx": $_2024_Wolf,
    "./islands/NewHeart.tsx": $NewHeart,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
