// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[color].jsx";
import * as $1 from "./routes/_middleware.js";
import * as $2 from "./routes/api/hue.js";
import * as $3 from "./routes/char/[color].jsx";
import * as $4 from "./routes/char/index.jsx";
import * as $5 from "./routes/index.jsx";
import * as $$0 from "./islands/Heart.jsx";

const manifest = {
  routes: {
    "./routes/[color].jsx": $0,
    "./routes/_middleware.js": $1,
    "./routes/api/hue.js": $2,
    "./routes/char/[color].jsx": $3,
    "./routes/char/index.jsx": $4,
    "./routes/index.jsx": $5,
  },
  islands: {
    "./islands/Heart.jsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
