// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[color].jsx";
import * as $1 from "./routes/api/_middleware.js";
import * as $2 from "./routes/api/hue.js";
import * as $3 from "./routes/char/[color].jsx";
import * as $4 from "./routes/char/index.jsx";
import * as $5 from "./routes/index.jsx";
import * as $6 from "./routes/robots.txt.jsx";
import * as $7 from "./routes/rotation/[rotation].jsx";
import * as $8 from "./routes/summerbay.jsx";
import * as $9 from "./routes/wolfe.jsx";
import * as $$0 from "./islands/Background.jsx";
import * as $$1 from "./islands/Heart.jsx";
import * as $$2 from "./islands/LaserWaveform.jsx";
import * as $$3 from "./islands/SummerBay.jsx";
import * as $$4 from "./islands/Wolf.jsx";

const manifest = {
  routes: {
    "./routes/[color].jsx": $0,
    "./routes/api/_middleware.js": $1,
    "./routes/api/hue.js": $2,
    "./routes/char/[color].jsx": $3,
    "./routes/char/index.jsx": $4,
    "./routes/index.jsx": $5,
    "./routes/robots.txt.jsx": $6,
    "./routes/rotation/[rotation].jsx": $7,
    "./routes/summerbay.jsx": $8,
    "./routes/wolfe.jsx": $9,
  },
  islands: {
    "./islands/Background.jsx": $$0,
    "./islands/Heart.jsx": $$1,
    "./islands/LaserWaveform.jsx": $$2,
    "./islands/SummerBay.jsx": $$3,
    "./islands/Wolf.jsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
